version: '3.7'

services:
  taskproject:
    image: taskproject:dev
    container_name: taskproject
    build: .docker/development
    volumes:
      - .:/api
    ports:
      - ${API_PORT}:3000
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mongo
    container_name: taskproject-db
    restart: always
    volumes:
      - taskproject-db:/data/db
    ports:
      - '27018:27017'
    networks:
      - backend

volumes:
  taskproject-db:

networks:
  backend:
    driver: bridge